version: '3'
services:
  nginx_load_balancers:
    image: nginx
    build: 
            context: .
            dockerfile: Dockerfile
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
    ports:
      - '8081:3001'
  app1:
    image: node-apps
    environment:
      - APPID=1111
  app2:
    image: node-apps
    environment:
      - APPID=2222
  app3:
    image: node-apps
    environment:
      - APPID=3333
  app4:
    image: node-apps
    environment:
      - APPID=4444